# encoding: ascii-8bit

source ENV['RUBYGEMS_URL'] || "https://rubygems.org"

gem 'ruby-termios', '>= 0.9' if RbConfig::CONFIG['target_os'] !~ /mswin|mingw|cygwin/i and RUBY_ENGINE == 'ruby'

gemspec :name => 'openc3'

# Include the rails gems for the convenience of custom microservice plugins
gem 'rails', '~> 7.0.0'
gem 'bootsnap', '>= 1.9.3', require: false
gem 'rack-cors', '~> 2.0'
gem 'tzinfo-data'
# httpclient hasn't been released since 2016 so use Shopify's updated one
gem 'httpclient', git: 'https://github.com/Shopify/httpclient'
