# encoding: ascii-8bit

source ENV['RUBYGEMS_URL'] || "https://rubygems.org"

gemspec :name => 'openc3'

# Include the rails gems for the convenience of custom microservice plugins
gem 'bootsnap', '>= 1.9.3', require: false
gem 'rack-cors', '~> 2.0'
gem 'rails', '~> 7.2.0'
gem 'tzinfo-data'
gem 'ruby-termios', '>= 1.0'
