# encoding: ascii-8bit

source ENV['RUBYGEMS_URL'] || "https://rubygems.org"

gem 'ruby-termios', '>= 0.9' if RbConfig::CONFIG['target_os'] !~ /mswin|mingw|cygwin/i and RUBY_ENGINE == 'ruby'

gemspec :name => 'openc3'

# Include the rails gems for the convenience of custom microservice plugins
gem 'bootsnap', '>= 1.9.3', require: false
gem 'rack-cors', '~> 2.0'
gem 'rails', '~> 7.1.0'
gem 'tzinfo-data'

group :test, :development do
  gem 'mock_redis', '0.44'
  gem 'rspec-rails', '~> 6.0'
  gem 'simplecov', '~> 0.20'
  gem 'simplecov-cobertura', '~> 2.1'
end
