coverage:
  status:
    # Disable patch reporting which we don't really use anyway
    # See https://docs.codecov.com/docs/commit-status#patch-status
    patch: off
    project:
      default:
        target: auto
        # Coverage can drop by 50% and still be a success (don't fail the build)
        threshold: 50%
      openc3-ruby:
        threshold: 50%
        paths:
          - openc3/openc3/lib
        flags:
          - ruby-backend
      frontend:
        threshold: 50%
        paths:
          - openc3-cosmos-init
        flags:
          - frontend
      api:
        threshold: 50%
        paths:
          - openc3-cosmos-cmd-tlm-api
          - openc3-cosmos-script-runner-api
        flags:
          - ruby-api

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 50%
