# Core-specific overrides for compose.yaml generation
mode: core

# License header
LICENSE_HEADER: |
  # Copyright 2022 Ball Aerospace & Technologies Corp.
  # All Rights Reserved.
  #
  # This program is free software; you can modify and/or redistribute it
  # under the terms of the GNU Affero General Public License
  # as published by the Free Software Foundation; version 3 with
  # attribution addendums as found in the LICENSE.txt
  #
  # This program is distributed in the hope that it will be useful,
  # but WITHOUT ANY WARRANTY; without even the implied warranty of
  # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  # GNU Affero General Public License for more details.

  # Modified by OpenC3, Inc.
  # All changes Copyright 2025, OpenC3, Inc.
  # All Rights Reserved
  #
  # This file may also be used under the terms of a commercial license
  # if purchased from OpenC3, Inc.

# Image configuration
REGISTRY_VAR: OPENC3_REGISTRY
NAMESPACE_VAR: OPENC3_NAMESPACE
TAG_VAR: OPENC3_TAG
IMAGE_PREFIX: openc3-

# Directory names
REDIS_DIR: openc3-redis
TRAEFIK_DIR: openc3-traefik

# Service-specific image names
CMD_TLM_API_IMAGE: openc3-cosmos-cmd-tlm-api
SCRIPT_RUNNER_API_IMAGE: openc3-cosmos-script-runner-api
COSMOS_INIT_IMAGE: openc3-cosmos-init

# Environment file
ENV_FILE: .env

# Minio ports (uncomment for testing)
MINIO_PORTS: |2
      # Uncomment to run unit tests against the minio server
      # ports:
      #   - "127.0.0.1:9000:9000"

# CMD TLM API specific
CMD_TLM_API_SERVICE_PASSWORD: |2
        OPENC3_SERVICE_PASSWORD: "${OPENC3_SERVICE_PASSWORD}"

CMD_TLM_API_EXTRA_HOSTS: |2
      extra_hosts:
        - host.docker.internal:host-gateway

# Script Runner API specific
SCRIPT_RUNNER_API_SERVICE_PASSWORD: |2
        OPENC3_SERVICE_PASSWORD: "${OPENC3_SERVICE_PASSWORD}"

# No enterprise services in core
ENTERPRISE_SERVICES: ""

# Operator configuration for core
OPERATOR_PORTS: |2
      # ports:
      #   - "127.0.0.1:7779:7779" # Open port for the demo router
      #   - "127.0.0.1:8081:8081/udp" # Open a udp port

OPERATOR_VOLUME_COMMENTS: |2
        # Add access to the entire C drive on Windows
        # - "/c:/c"
        # Create a dropbox and archive folder for ingest by FileInterface and PreidentifiedRouter
        # - /Users/jmthomas/dropbox:/dropbox
        # - /Users/jmthomas/archive:/archive

OPERATOR_CI_ENV: |2
        # CI in set in Github actions, changes the Demo TLM_LOG_CYCLE_TIME
        # By not setting a value it pases the environment variable from the shell
        # straight to the container and doesn't complain if CI is not set
        CI: "${CI:-}"

OPERATOR_SERVICE_PASSWORD: |2
        OPENC3_SERVICE_PASSWORD: "${OPENC3_SERVICE_PASSWORD}"

OPERATOR_COMMAND: "\n"

# Init configuration for core
INIT_CI_ENV: |2
        # CI in set in Github actions, changes the Demo TLM_LOG_CYCLE_TIME
        # By not setting a value it pases the environment variable from the shell
        # straight to the container and doesn't complain if CI is not set
        CI: "${CI:-}"

# No enterprise-only services
ENTERPRISE_ONLY_SERVICES: ""

# No enterprise volumes
ENTERPRISE_VOLUMES: ""
