# Copyright 2026 OpenC3, Inc.
# All Rights Reserved.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE.md for more details.
#
# This file may also be used under the terms of a commercial license
# if purchased from OpenC3, Inc.

# GENERATED by tools/generate_singleton_stubs.py -- regenerate after changing
# the public API of a singleton class, or run `just stubs-check` to detect drift.
#
# openc3.system.system uses a metaclass that forwards attribute access to cls.instance().
# That is invisible to type checkers, so the forwarded instance methods are
# declared here as classmethods to describe the API as it is actually called.
#
# Types shown as Incomplete are unannotated in the source. Hand-refining them
# improves checking; use --diff before regenerating to see what would be lost.

from _typeshed import Incomplete

from openc3.config.config_parser import ConfigParser as ConfigParser
from openc3.environment import OPENC3_CONFIG_BUCKET as OPENC3_CONFIG_BUCKET
from openc3.environment import OPENC3_SCOPE as OPENC3_SCOPE
from openc3.packets.commands import Commands as Commands
from openc3.packets.limits import Limits as Limits
from openc3.packets.packet_config import PacketConfig as PacketConfig
from openc3.packets.telemetry import Telemetry as Telemetry
from openc3.system.target import Target as Target
from openc3.top_level import add_to_search_path as add_to_search_path
from openc3.utilities.bucket import Bucket as Bucket
from openc3.utilities.logger import Logger as Logger
from openc3.utilities.store import Store as Store

class SystemMeta(type):
    @property
    def targets(cls): ...
    @targets.setter
    def targets(cls, value) -> None: ...
    @property
    def packet_config(cls): ...
    @packet_config.setter
    def packet_config(cls, value) -> None: ...
    @property
    def commands(cls): ...
    @commands.setter
    def commands(cls, value) -> None: ...
    @property
    def telemetry(cls): ...
    @telemetry.setter
    def telemetry(cls, value) -> None: ...
    @property
    def limits(cls): ...
    @limits.setter
    def limits(cls, value) -> None: ...

class System(metaclass=SystemMeta):
    instance_obj: Incomplete
    instance_mutex: Incomplete
    post_instance_callbacks: Incomplete

    @classmethod
    def limits_set(cls, scope=...): ...
    @classmethod
    def add_post_instance_callback(cls, callback) -> None: ...
    @classmethod
    def setup_targets(cls, target_names, base_dir, scope=...) -> None: ...
    @classmethod
    def instance(cls, target_names=None, target_config_dir=None): ...
    @classmethod
    def dynamic_update(cls, dynamic_packets, cmd_or_tlm: str = "TELEMETRY", affect_ids: bool = False) -> None: ...
    targets: Incomplete
    packet_config: Incomplete
    commands: Incomplete
    telemetry: Incomplete
    limits: Incomplete

    def __init__(self, target_names, target_config_dir) -> None: ...
    @classmethod
    def add_target(cls, target_name, target_config_dir) -> None: ...
