# Copyright 2026 OpenC3, Inc.
# All Rights Reserved.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE.md for more details.
#
# This file may also be used under the terms of a commercial license
# if purchased from OpenC3, Inc.

# GENERATED by tools/generate_singleton_stubs.py -- regenerate after changing
# the public API of a singleton class, or run `just stubs-check` to detect drift.
#
# openc3.topics.topic uses a metaclass that forwards attribute access to cls.instance().
# That is invisible to type checkers, so the forwarded instance methods are
# declared here as classmethods to describe the API as it is actually called.
#
# Types shown as Incomplete are unannotated in the source. Hand-refining them
# improves checking; use --diff before regenerating to see what would be lost.

from openc3.utilities.store import EphemeralStore as EphemeralStore

class TopicMeta(type):
    def __getattr__(cls, func): ...

class Topic(metaclass=TopicMeta):
    @classmethod
    def clear_topics(cls, topics, maxlen: int = 0, db_shard: int = 0) -> None: ...
    @classmethod
    def topics(cls, key, scope, db_shard: int = 0): ...
    @classmethod
    def get_cnt(cls, topic, db_shard: int = 0): ...
    @classmethod
    def write_topic(cls, topic, msg_hash, id: str = "*", maxlen=None, approximate: bool = True, db_shard: int = 0): ...
    @classmethod
    def read_topics(cls, topics, offsets=None, timeout_ms: int = 1000, count=None, db_shard: int = 0): ...
    @classmethod
    def get_newest_message(cls, topic, db_shard: int = 0): ...
    @classmethod
    def get_oldest_message(cls, topic, db_shard: int = 0): ...
    @classmethod
    def get_last_offset(cls, topic, db_shard: int = 0): ...
    @classmethod
    def update_topic_offsets(cls, topics, db_shard: int = 0): ...
    @classmethod
    def trim_topic(cls, topic, minid, approximate: bool = True, limit: int = 0, db_shard: int = 0): ...
    @classmethod
    def group_topics_by_db_shard(cls, topics, target_pattern, scope): ...
    @staticmethod
    def all_same_db_shard(db_shard_groups): ...
    @classmethod
    def write_ack(cls, topic, result, msg_id, db_shard: int = 0) -> None: ...
