ARG OPENC3_UBI_REGISTRY=registry1.dso.mil
ARG OPENC3_UBI_IMAGE=ironbank/redhat/ubi/ubi9-minimal
ARG OPENC3_UBI_TAG=9.6

FROM ${OPENC3_UBI_REGISTRY}/${OPENC3_UBI_IMAGE}:${OPENC3_UBI_TAG} AS base
FROM base AS build

LABEL maintainer="support@openc3.com"

USER root

# We require a local certificate file so set that up.
# You must place a valid cacert.pem file in your OpenC3 development folder for this work
# Comment out these lines if this is not required in your environment
COPY cacert.pem /devel/cacert.pem
ENV SSL_CERT_FILE=/devel/cacert.pem
ENV CURL_CA_BUNDLE=/devel/cacert.pem
ENV REQUESTS_CA_BUNDLE=/devel/cacert.pem
ENV NODE_EXTRA_CA_CERTS=/devel/cacert.pem

COPY *.tar.gz /tmp/

ARG PACKAGES="gcc-c++ patch readline zlib zlib-devel \
    openssl-devel make autoconf automake \
    ca-certificates \
    glibc-static tar systemd-devel unzip"

RUN rm /etc/yum.repos.d/*
COPY ./ubi.repo /etc/yum.repos.d/ubi.repo

# ruby - https://www.ruby-lang.org/en/downloads/releases/
# tini - https://github.com/krallin/tini
RUN microdnf update -y \
    && microdnf install -y --setopt=tsflags=nodocs $PACKAGES \
    && rm -rf /var/cache/dnf/ /var/tmp/* /tmp/* /var/tmp/.???* /tmp/.???*

COPY valkey-9.0.1.tar.gz /tmp/valkey.tar.gz

WORKDIR /tmp

RUN set -eux; \
	mkdir -p /usr/src/valkey; \
	tar -xzf valkey.tar.gz -C /usr/src/valkey --strip-components=1; \
	rm valkey.tar.gz; \
	\
# disable Valkey protected mode [1] as it is unnecessary in context of Docker
# (ports are not automatically exposed when running inside Docker, but rather explicitly by specifying -p / -P)
	grep -E '^ *createBoolConfig[(]"protected-mode",.*, *1 *,.*[)],$' /usr/src/valkey/src/config.c; \
	sed -ri 's!^( *createBoolConfig[(]"protected-mode",.*, *)1( *,.*[)],)$!\10\2!' /usr/src/valkey/src/config.c; \
	grep -E '^ *createBoolConfig[(]"protected-mode",.*, *0 *,.*[)],$' /usr/src/valkey/src/config.c; \
# for future reference, we modify this directly in the source instead of just supplying a default configuration flag because apparently "if you specify any argument to valkey-server, [it assumes] you are going to specify everything"
# (more exactly, this makes sure the default behavior of "save on SIGTERM" stays functional by default)
	\
	echo "Version 9.0.1 is 8.1 or higher - enabling USE_FAST_FLOAT"; \
	export BUILD_TLS=yes USE_FAST_FLOAT=yes; \
	export USE_SYSTEMD=yes; \
  export MALLOC=libc; \
	make -C /usr/src/valkey -j "$(nproc)" all; \
	make -C /usr/src/valkey install; \
	\
	serverMd5="$(md5sum /usr/local/bin/valkey-server | cut -d' ' -f1)"; export serverMd5; \
	find /usr/local/bin/valkey* -maxdepth 0 \
		-type f -not -name valkey-server \
		-exec sh -eux -c ' \
			md5="$(md5sum "$1" | cut -d" " -f1)"; \
			test "$md5" = "$serverMd5"; \
		' -- '{}' ';' \
		-exec ln -svfT 'valkey-server' '{}' ';' \
	; \
	\
	echo '{"spdxVersion":"SPDX-2.3","SPDXID":"SPDXRef-DOCUMENT","name":"valkey-server-sbom","packages":[{"name":"valkey-server","versionInfo":"9.0.1","SPDXID":"SPDXRef-Package--valkey-server","externalRefs":[{"referenceCategory":"PACKAGE-MANAGER","referenceType":"purl","referenceLocator":"pkg:generic/valkey-server@9.0.1?os_name=debian&os_version=trixie"}],"licenseDeclared":"BSD-3-Clause"}]}' > /usr/local/valkey.spdx.json

FROM base

ENV VALKEY_VERSION=9.0.1

LABEL org.opencontainers.image.source="https://github.com/valkey-io/valkey"

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN set -eux; \
	groupadd -r -g 1001 valkey; \
	useradd -r -g valkey -u 1001 valkey

ARG RUNTIME_PACKAGES="tzdata openssl-libs"

# runtime dependencies
RUN set -eux; \
	microdnf update -y \
  && microdnf install -y --setopt=tsflags=nodocs $RUNTIME_PACKAGES \
	&& rm -rf /var/cache/dnf/

# Install valkey built earlier
COPY --from=build /usr/local /usr/local
RUN mkdir /data && \
	chown valkey:valkey /data && \
	mkdir -p /run/valkey && \
	chown valkey:valkey /run/valkey && \
	valkey-cli --version && \
	valkey-server --version
WORKDIR /data

COPY docker-entrypoint.sh /usr/local/bin/
ENTRYPOINT ["docker-entrypoint.sh"]

# Below is our standard Valkey changes to the published image
COPY cacert.pem /devel/cacert.pem
ENV SSL_CERT_FILE=/devel/cacert.pem
ENV CURL_CA_BUNDLE=/devel/cacert.pem
ENV REQUESTS_CA_BUNDLE=/devel/cacert.pem
ENV NODE_EXTRA_CA_CERTS=/devel/cacert.pem

RUN mkdir /config
COPY redis.conf /config/.
COPY redis_ephemeral.conf /config/.
COPY users.acl /config/.
COPY --chmod=0755 ./docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

RUN mkdir -p /data && chown valkey:valkey /data
RUN ["chmod", "-R", "777", "/data/"]
RUN mkdir -p /home/data && chown valkey:valkey /home/data
RUN ["chmod", "-R", "777", "/home/data/"]

EXPOSE 6379
EXPOSE 6380
USER valkey

WORKDIR /data
CMD [ "valkey-server", "/config/redis.conf" ]
