# Copyright 2026 OpenC3, Inc.
# All Rights Reserved.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE.md for more details.
#
# This file may also be used under the terms of a commercial license
# if purchased from OpenC3, Inc.

# GENERATED by tools/generate_singleton_stubs.py -- regenerate after changing
# the public API of a singleton class, or run `just stubs-check` to detect drift.
#
# openc3.utilities.logger uses a metaclass that forwards attribute access to cls.instance().
# That is invisible to type checkers, so the forwarded instance methods are
# declared here as classmethods to describe the API as it is actually called.
#
# Types shown as Incomplete are unannotated in the source. Hand-refining them
# improves checking; use --diff before regenerating to see what would be lost.

from enum import IntEnum

from _typeshed import Incomplete

from openc3.environment import *
from openc3.utilities.store_queued import EphemeralStoreQueued as EphemeralStoreQueued

CLASS_ATTRS: Incomplete
INSTANCE_ATTRS: Incomplete

class LoggerMeta(type): ...

class LogLevel(IntEnum):
    DEBUG = 0
    INFO = 1
    WARN = 2
    ERROR = 3
    FATAL = 4

class Logger(metaclass=LoggerMeta):
    instance_mutex: Incomplete
    my_instance: Incomplete
    scope = OPENC3_SCOPE
    DEBUG: Incomplete
    INFO: Incomplete
    WARN: Incomplete
    ERROR: Incomplete
    FATAL: Incomplete
    LOG: str
    NOTIFICATION: str
    ALERT: str
    EPHEMERAL: str
    stdout: bool
    level: Incomplete
    detail_string: Incomplete
    container_name: Incomplete
    microservice_name: Incomplete
    no_store: bool

    def __init__(self, level=...) -> None: ...
    @classmethod
    def instance(cls, level=...): ...
    @classmethod
    def debug(cls, message=None, scope=None, user=None, type=..., url=None, other=None) -> None: ...
    @classmethod
    def info(cls, message=None, scope=None, user=None, type=..., url=None, other=None) -> None: ...
    @classmethod
    def warn(cls, message=None, scope=None, user=None, type=..., url=None, other=None) -> None: ...
    @classmethod
    def error(cls, message=None, scope=None, user=None, type=..., url=None, other=None) -> None: ...
    @classmethod
    def fatal(cls, message=None, scope=None, user=None, type=..., url=None, other=None) -> None: ...
    @classmethod
    def build_log_data(cls, log_level: str, message: str | None, user=None, type=None, url=None, other=None): ...
    @classmethod
    def log_message(cls, log_level: str, message: str | None, scope, user, type, url, other=None): ...
