# Copyright 2026 OpenC3, Inc.
# All Rights Reserved.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE.md for more details.
#
# This file may also be used under the terms of a commercial license
# if purchased from OpenC3, Inc.

# GENERATED by tools/generate_singleton_stubs.py -- regenerate after changing
# the public API of a singleton class, or run `just stubs-check` to detect drift.
#
# openc3.utilities.store_implementation uses a metaclass that forwards attribute access to cls.instance().
# That is invisible to type checkers, so the forwarded instance methods are
# declared here as classmethods to describe the API as it is actually called.
#
# Types shown as Incomplete are unannotated in the source. Hand-refining them
# improves checking; use --diff before regenerating to see what would be lost.

from collections.abc import Generator
from contextlib import contextmanager

from _typeshed import Incomplete

from openc3.environment import *
from openc3.utilities.connection_pool import ConnectionPool as ConnectionPool

class StoreConnectionPool(ConnectionPool):
    @contextmanager
    def pipelined(self) -> Generator[None]: ...
    @contextmanager
    def get(self) -> Generator[Incomplete]: ...

class StoreMeta(type):
    _CLASS_ATTRS: Incomplete

    def __getattribute__(cls, func): ...

class Store(metaclass=StoreMeta):
    my_instances: Incomplete
    instance_mutex: Incomplete
    _db_shard_cache: Incomplete
    _db_shard_cache_lock: Incomplete
    DB_SHARD_CACHE_TIMEOUT: int

    @classmethod
    def instance(cls, pool_size: int = 100, db_shard: int = 0): ...
    @classmethod
    def db_shard_for_target(cls, target_name, scope: str = "DEFAULT"): ...
    def __getattr__(self, func): ...
    db_shard: Incomplete
    redis_host: Incomplete
    redis_port: Incomplete
    redis_pool: Incomplete
    topic_offsets: Incomplete
    pipelines: Incomplete

    def __init__(self, pool_size: int = 10, db_shard: int = 0) -> None: ...
    @classmethod
    def build_redis(cls): ...
    @classmethod
    def get_oldest_message(cls, topic): ...
    @classmethod
    def get_newest_message(cls, topic): ...
    @classmethod
    def get_last_offset(cls, topic): ...
    @classmethod
    def update_topic_offsets(cls, topics): ...
    @classmethod
    def read_topics(
        cls, topics, offsets=None, timeout_ms: int = 1000, count=None
    ) -> Generator[Incomplete, None, Incomplete]: ...
    @classmethod
    def write_topic(cls, topic, msg_hash, id: str = "*", maxlen=None, approximate: bool = True): ...
    @classmethod
    def trim_topic(cls, topic, minid, approximate: bool = True, limit: int = 0): ...

class EphemeralStore(Store):
    my_instances: Incomplete
    redis_host: Incomplete
    redis_port: Incomplete
    redis_pool: Incomplete

    def __init__(self, pool_size: int = 10, db_shard: int = 0) -> None: ...
