# Copyright 2026 OpenC3, Inc.
# All Rights Reserved.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE.md for more details.
#
# This file may also be used under the terms of a commercial license
# if purchased from OpenC3, Inc.

# GENERATED by tools/generate_singleton_stubs.py -- regenerate after changing
# the public API of a singleton class, or run `just stubs-check` to detect drift.
#
# openc3.utilities.store_queued uses a metaclass that forwards attribute access to cls.instance().
# That is invisible to type checkers, so the forwarded instance methods are
# declared here as classmethods to describe the API as it is actually called.
#
# Types shown as Incomplete are unannotated in the source. Hand-refining them
# improves checking; use --diff before regenerating to see what would be lost.

from _typeshed import Incomplete

from openc3.utilities.sleeper import Sleeper as Sleeper
from openc3.utilities.store import EphemeralStore as EphemeralStore
from openc3.utilities.store import Store as Store
from openc3.utilities.store import StoreMeta as StoreMeta

def kill_thread(owner, thread, timeout: float = 1.0) -> None: ...

class StoreQueued(metaclass=StoreMeta):
    my_instances: Incomplete
    instance_mutex: Incomplete

    @classmethod
    def instance(cls, update_interval: int = 1, db_shard: int = 0): ...
    update_interval: Incomplete
    db_shard: Incomplete
    store: Incomplete
    store_queue: Incomplete
    update_sleeper: Incomplete
    update_thread: Incomplete

    def __init__(self, update_interval, db_shard: int = 0) -> None: ...
    @classmethod
    def set_update_interval(cls, interval) -> None: ...
    @classmethod
    def process_queue(cls) -> None: ...
    @classmethod
    def store_thread_body(cls) -> None: ...
    @classmethod
    def shutdown(cls) -> None: ...
    def __getattr__(self, func): ...
    @classmethod
    def store_instance(cls): ...
    @classmethod
    def graceful_kill(cls) -> None: ...

class EphemeralStoreQueued(StoreQueued):
    my_instances: Incomplete

    def store_instance(self): ...
