#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["mypy>=1.14,<2", "ruff>=0.15,<0.17"]
# ///

# Copyright 2026 OpenC3, Inc.
# All Rights Reserved.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE.md for more details.
#
# This file may also be used under the terms of a commercial license
# if purchased from OpenC3, Inc.

"""Generate .pyi stubs for the singleton-metaclass classes.

Several OpenC3 classes (Logger, Store, StoreQueued, System, Topic) are used as
singletons: the class itself is the public API and a metaclass __getattribute__
forwards every access to cls.instance(). That forwarding happens at runtime and
is invisible to static type checkers, so `Logger.info("msg")` looks like an
unbound call of the instance method `info` and "msg" gets bound to `self`:

    error[invalid-argument-type] Argument to function `Logger.info` is
    incorrect: Expected `Logger`, found `str`

This script generates stubs that describe the *effective* API by promoting the
forwarded instance methods to classmethods, so both `Logger.info("msg")` and
`Logger.instance().info("msg")` check correctly while wrong argument types and
unknown attributes are still reported.

    ./tools/generate_singleton_stubs.py            # write stubs
    ./tools/generate_singleton_stubs.py --check     # fail if stubs are stale
    ./tools/generate_singleton_stubs.py --diff      # show what would change

Generated stubs are intentionally coarse: mypy's stubgen emits `Incomplete`
(an alias for Any) wherever the source has no annotation. That is enough to fix
the self-binding errors. Refine a stub by hand for better checking, then use
--diff to see what regeneration would drop before committing.
"""

import argparse
import ast
import difflib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


PACKAGE_ROOT = Path(__file__).resolve().parent.parent
PACKAGE = PACKAGE_ROOT / "openc3"

HEADER = """# Copyright 2026 OpenC3, Inc.
# All Rights Reserved.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE.md for more details.
#
# This file may also be used under the terms of a commercial license
# if purchased from OpenC3, Inc.

# GENERATED by tools/generate_singleton_stubs.py -- regenerate after changing
# the public API of a singleton class, or run `just stubs-check` to detect drift.
#
# {module} uses a metaclass that forwards attribute access to cls.instance().
# That is invisible to type checkers, so the forwarded instance methods are
# declared here as classmethods to describe the API as it is actually called.
#
# Types shown as Incomplete are unannotated in the source. Hand-refining them
# improves checking; use --diff before regenerating to see what would be lost.
"""

# Methods that stay instance methods: they are real constructors / protocol
# hooks, not part of the forwarded singleton API
KEEP_INSTANCE = {"__init__", "__new__", "__getattr__", "__setattr__", "__getattribute__"}

# Attribute-forwarding hooks. On a metaclass these make every attribute access
# on the class resolve to Any, which silences typos and unknown attributes
FORWARDING_HOOKS = {"__getattr__", "__getattribute__", "__setattr__"}

# Modules whose singleton API the stub describes completely. Dropping the
# forwarding hooks there restores unknown-attribute checking (Logger.infoo is
# reported) at no cost.
#
# Store, StoreQueued and Topic are deliberately absent: they forward arbitrary
# Valkey commands (Store.zrangebyscore, Store.hgetall, ...) that the stub cannot
# enumerate, so dropping their hooks reports ~73 attributes that do exist at
# runtime. Typing those properly means annotating the forwarded client, not
# removing the hook.
STRICT_MODULES = {
    "openc3/utilities/logger.py",
}


def find_singleton_modules() -> list[Path]:
    """Return the source files that define a class with a custom metaclass."""
    found = []
    for path in sorted(PACKAGE.rglob("*.py")):
        try:
            tree = ast.parse(path.read_text())
        except SyntaxError:
            continue
        if any(
            isinstance(node, ast.ClassDef) and any(kw.arg == "metaclass" for kw in node.keywords)
            for node in ast.walk(tree)
        ):
            found.append(path)
    return found


class PromoteToClassmethod(ast.NodeTransformer):
    """Rewrite forwarded instance methods of metaclass-using classes as classmethods."""

    def __init__(self, keep_hooks: bool = False):
        self.promoted: list[str] = []
        self.dropped: list[str] = []
        self.keep_hooks = keep_hooks

    def visit_ClassDef(self, node: ast.ClassDef) -> ast.ClassDef:
        if any(isinstance(base, ast.Name) and base.id == "type" for base in node.bases):
            if not self.keep_hooks:
                kept = []
                for item in node.body:
                    if isinstance(item, ast.FunctionDef) and item.name in FORWARDING_HOOKS:
                        self.dropped.append(f"{node.name}.{item.name}")
                        continue
                    kept.append(item)
                node.body = kept or [ast.Expr(value=ast.Constant(value=Ellipsis))]
            return node
        if not any(kw.arg == "metaclass" for kw in node.keywords):
            return node
        for item in node.body:
            if not isinstance(item, ast.FunctionDef):
                continue
            if item.name in KEEP_INSTANCE:
                continue
            decorators = {d.id for d in item.decorator_list if isinstance(d, ast.Name)}
            if decorators & {"classmethod", "staticmethod", "property"}:
                continue
            if not item.args.args or item.args.args[0].arg != "self":
                continue
            item.args.args[0].arg = "cls"
            item.decorator_list.insert(0, ast.Name(id="classmethod", ctx=ast.Load()))
            self.promoted.append(f"{node.name}.{item.name}")
        return node


def run_stubgen(sources: list[Path], out_dir: Path) -> None:
    # mypy ships compiled, so stubgen is only runnable as its console script,
    # which uv places next to the interpreter running this script
    stubgen = Path(sys.executable).parent / "stubgen"
    if not stubgen.exists():
        stubgen = Path(shutil.which("stubgen") or "")
    if not stubgen.exists():
        raise SystemExit("stubgen not found -- run this script with `uv run --script` or `just stubs`")
    subprocess.run(
        [str(stubgen), "--include-private", "-o", str(out_dir), *map(str, sources)],
        check=True,
        cwd=PACKAGE_ROOT,
        stdout=subprocess.DEVNULL,
    )


def ruff_clean(text: str) -> str:
    """Sort imports and format, so generated stubs pass the repo's ruff config."""
    ruff = Path(sys.executable).parent / "ruff"
    if not ruff.exists():
        found = shutil.which("ruff")
        if found is None:
            return text
        ruff = Path(found)

    for argv in (
        ["check", "--stdin-filename", "stub.pyi", "--select", "I", "--fix", "-"],
        ["format", "--stdin-filename", "stub.pyi", "-"],
    ):
        done = subprocess.run([str(ruff), *argv], input=text, capture_output=True, text=True)
        if done.stdout:
            text = done.stdout
    return text


def build_stub(raw: Path, module: str, keep_hooks: bool = False) -> tuple[str, list[str], list[str]]:
    tree = ast.parse(raw.read_text())
    transformer = PromoteToClassmethod(keep_hooks=keep_hooks)
    transformer.visit(tree)
    body = ast.unparse(ast.fix_missing_locations(tree))
    stub = ruff_clean(HEADER.format(module=module) + "\n" + body + "\n")
    return stub, transformer.promoted, transformer.dropped


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit non-zero if any stub is out of date")
    parser.add_argument("--diff", action="store_true", help="print a diff instead of writing")
    parser.add_argument(
        "--keep-hooks",
        action="store_true",
        help="keep metaclass __getattr__/__getattribute__ everywhere, ignoring STRICT_MODULES",
    )
    args = parser.parse_args()

    sources = find_singleton_modules()
    if not sources:
        print("no singleton-metaclass modules found", file=sys.stderr)
        return 1

    stale = []
    with tempfile.TemporaryDirectory() as tmp:
        out_dir = Path(tmp)
        run_stubgen(sources, out_dir)

        for source in sources:
            relative = source.relative_to(PACKAGE_ROOT)
            raw = out_dir / relative.with_suffix(".pyi")
            if not raw.exists():
                print(f"stubgen produced no stub for {relative}", file=sys.stderr)
                return 1

            module = ".".join(relative.with_suffix("").parts)
            keep_hooks = args.keep_hooks or relative.as_posix() not in STRICT_MODULES
            stub, promoted, dropped = build_stub(raw, module, keep_hooks=keep_hooks)
            target = source.with_suffix(".pyi")
            current = target.read_text() if target.exists() else ""

            if args.diff or args.check:
                if current != stub:
                    stale.append(target.relative_to(PACKAGE_ROOT))
                    if args.diff:
                        sys.stdout.writelines(
                            difflib.unified_diff(
                                current.splitlines(keepends=True),
                                stub.splitlines(keepends=True),
                                fromfile=f"a/{target.relative_to(PACKAGE_ROOT)}",
                                tofile=f"b/{target.relative_to(PACKAGE_ROOT)}",
                            )
                        )
                continue

            target.write_text(stub)
            print(f"wrote {target.relative_to(PACKAGE_ROOT)} ({len(promoted)} promoted, {len(dropped)} hooks dropped)")
            for name in promoted:
                print(f"    classmethod  {name}")
            for name in dropped:
                print(f"    dropped      {name}")

    if stale:
        verb = "differ from" if args.diff else "are out of date with"
        print(f"\n{len(stale)} stub(s) {verb} the source:", file=sys.stderr)
        for path in stale:
            print(f"    {path}", file=sys.stderr)
        print("\nRun `just stubs` to regenerate.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
