ARG OPENC3_UBI_REGISTRY=registry1.dso.mil
ARG OPENC3_UBI_IMAGE=ironbank/redhat/ubi/ubi9-minimal
ARG OPENC3_UBI_TAG=9.5

FROM ${OPENC3_UBI_REGISTRY}/${OPENC3_UBI_IMAGE}:${OPENC3_UBI_TAG}

LABEL maintainer="support@openc3.com"

USER root

ARG RUBYGEMS_URL=https://rubygems.org
ENV RUBYGEMS_URL=${RUBYGEMS_URL}
ARG PYPI_URL=https://pypi.org
ENV PYPI_URL=${PYPI_URL}

# We require a local certificate file so set that up.
# You must place a valid cacert.pem file in your OpenC3 development folder for this work
# Comment out these lines if this is not required in your environment
COPY cacert.pem /devel/cacert.pem
ENV SSL_CERT_FILE=/devel/cacert.pem
ENV CURL_CA_BUNDLE=/devel/cacert.pem
ENV REQUESTS_CA_BUNDLE=/devel/cacert.pem
ENV NODE_EXTRA_CA_CERTS=/devel/cacert.pem

ENV NOKOGIRI_USE_SYSTEM_LIBRARIES=1

COPY .gemrc /root/.gemrc
RUN sed -i "s|RUBYGEMS_URL|${RUBYGEMS_URL}|g" /root/.gemrc
RUN cp /root/.gemrc /etc/gemrc
RUN cp /root/.gemrc /usr/local/etc/gemrc
ENV GEMRC=/etc/gemrc

COPY *.tar.gz /tmp/

COPY anycable* /usr/bin
RUN /usr/bin/anycable_install.sh

COPY shoreman.sh /usr/bin/shoreman

ARG PACKAGES="gcc-c++ patch readline zlib zlib-devel libffi-devel libedit \
    openssl-devel make nc bzip2 autoconf automake libtool sqlite-devel libpq-devel \
    python3.12 python3.12-devel python3.12-pip python3.12-numpy	ca-certificates less git \
    libxml2-devel libxslt-devel libyaml-devel cmake glibc-static vim procps unzip ncurses-devel"

RUN rm /etc/yum.repos.d/*
COPY ./ubi.repo /etc/yum.repos.d/ubi.repo

RUN microdnf update -y \
    && microdnf install -y --setopt=tsflags=nodocs $PACKAGES \
    && mkdir -p /usr/src \
    && tar -xzf /tmp/ruby-3.3.7.tar.gz -C /usr/src/ \
    && rm -f /tmp/ruby-3.3.7.tar.gz \
    && RUBY_DIR=$(ls /usr/src/ | grep ruby) \
    && cd /usr/src/${RUBY_DIR} \
    && ./configure --disable-install-doc --enable-shared \
    && make -j "$(nproc)" \
    && make install \
    && rm -rf /usr/src/${RUBY_DIR}
RUN cd / \
    && tar -xzf /tmp/tini-0.19.0.tar.gz -C /usr/src/ \
    && TINI_DIR=$(ls /usr/src/ | grep tini) \
    && rm -f /tmp/tini-0.19.0.tar.gz \
    && cd /usr/src/${TINI_DIR} \
    && CFLAGS="-DPR_SET_CHILD_SUBREAPER=36 -DPR_GET_CHILD_SUBREAPER=37" \
    && cmake . \
    && make \
    && make install \
    && rm -rf /usr/src/${TINI_DIR}
RUN cd / \
    && gem update --system \
    && gem install rake \
    && gem install google-protobuf \
    && gem install grpc \
    && gem cleanup \
    && bundle config build.nokogiri --use-system-libraries \
    && bundle config git.allow_insecure true \
    && rm -rf /var/cache/dnf/ /var/tmp/* /tmp/* /var/tmp/.???* /tmp/.???* \
    && rm /bin/python \
    && rm /bin/python3 \
    && ln -s /bin/python3.12 /bin/python \
    && ln -s /bin/python3.12 /bin/python3 \
    && ln -s /bin/pip3.12 /bin/pip \
    && ln -s /bin/pip3.12 /bin/pip3 \
    && python3 -m venv /openc3/venv \
    && source /openc3/venv/bin/activate \
    && pip3 config --global set global.index $PYPI_URL/pypi \
    && pip3 config --global set global.index-url $PYPI_URL/simple \
    && pip3 install --upgrade pip setuptools \
    && pip3 install poetry \
    && pip3 install poetry-plugin-export

# rbspy - https://github.com/rbspy/rbspy
COPY rbspy-x86_64-unknown-linux-gnu-0.32.0.tar.gz /opt/rbspy-x86_64-unknown-linux-gnu-0.32.0.tar.gz
RUN cd /opt \
  && tar -xzf rbspy-x86_64-unknown-linux-gnu-0.32.0.tar.gz \
  && cp rbspy-x86_64-unknown-linux-gnu /usr/local/bin/rbspy \
  && chmod +x /usr/local/bin/rbspy \
  && cd /opt \
  && rm rbspy-x86_64-unknown-linux-gnu \
  && rm rbspy-x86_64-unknown-linux-gnu-0.32.0.tar.gz

# htop - https://github.com/htop-dev/htop
COPY htop-3.4.1.tar.gz /opt/htop-3.4.1.tar.gz
RUN cd /opt \
  && tar -xzf htop-3.4.1.tar.gz \
  && cd htop-3.4.1 \
  && ./autogen.sh \
  && ./configure \
  && make \
  && make install \
  && cd /opt \
  && rm -rf htop-3.4.1 \
  && rm htop-3.4.1.tar.gz

# libsocketcan - used by libcsp - https://github.com/linux-can/libsocketcan
COPY libsocketcan-0.0.12.tar.gz /opt/libsocketcan-0.0.12.tar.gz
RUN cd /opt \
  && tar -xzf libsocketcan-0.0.12.tar.gz \
  && cd libsocketcan-0.0.12 \
  && autoreconf --force --install --symlink -Wall \
  && ./configure --libdir=/usr/lib64 \
  && make \
  && make install \
  && cd /opt \
  && rm -rf libsocketcan-0.0.12 \
  && rm libsocketcan-0.0.12.tar.gz

# libzmq - used by libcsp - https://github.com/zeromq/libzmq
COPY libzmq-34f7fa22022bed9e0e390ed3580a1c83ac4a2834.zip /opt/libzmq-34f7fa22022bed9e0e390ed3580a1c83ac4a2834.zip
RUN cd /opt \
  && unzip libzmq-34f7fa22022bed9e0e390ed3580a1c83ac4a2834.zip \
  && cd libzmq-34f7fa22022bed9e0e390ed3580a1c83ac4a2834 \
  && mkdir build \
  && cd build \
  && cmake .. -D WITH_PERF_TOOL=OFF -D ZMQ_BUILD_TESTS=OFF -D ENABLE_CPACK=OFF -D CMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=/usr/lib64 \
  && make \
  && make install \
  && cd /opt \
  && rm -rf libzmq-34f7fa22022bed9e0e390ed3580a1c83ac4a2834 \
  && rm libzmq-34f7fa22022bed9e0e390ed3580a1c83ac4a2834.zip

# libcsp - https://github.com/libcsp/libcsp
COPY libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632.zip /opt/libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632.zip
RUN cd /opt \
  && unzip libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632.zip \
  && cd libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632 \
  # Patches to fix compilation issues
  && sed -i '1s/^/#include <sys\/select.h>/' src/drivers/can/can_socketcan.c \
  && sed -i '2s/^/#include <endian.h>/' src/drivers/eth/eth_linux.c \
  && mkdir build \
  && cd build \
  && cmake .. -DCSP_ENABLE_PYTHON3_BINDINGS=ON -DCSP_USR_RTABLE=ON -DCMAKE_INSTALL_LIBDIR=/usr/lib64 \
  && make \
  && make install \
  && cp libcsp_py3* /lib64/python3.12/lib-dynload/. \
  && cd /opt \
  && rm -rf libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632 \
  && rm libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632.zip

# Set user and group
ENV IMAGE_USER=openc3
ENV IMAGE_GROUP=openc3
ENV USER_ID=1001
ENV GROUP_ID=1001
# The build time venv is at /openc3/venv and the runtime venv is at /gems/python_packages
# NOTE: This is declared as PYTHONUSERBASE: "/gems/python_packages" in compose.yaml
ENV PYTHONPATH=/openc3/venv/lib/python3.12/site-packages/:/gems/python_packages/lib/python3.12/site-packages/
RUN groupadd -g ${GROUP_ID} ${IMAGE_GROUP}
RUN useradd -u ${USER_ID} -g ${IMAGE_GROUP} -s /bin/sh ${IMAGE_USER}

# Switch to user
USER ${USER_ID}:${GROUP_ID}

ENTRYPOINT [ "/usr/local/bin/tini", "--" ]
