ARG OPENC3_UBI_REGISTRY=registry1.dso.mil
ARG OPENC3_UBI_IMAGE=ironbank/redhat/ubi/ubi9-minimal
ARG OPENC3_UBI_TAG=9.6

FROM ${OPENC3_UBI_REGISTRY}/${OPENC3_UBI_IMAGE}:${OPENC3_UBI_TAG}

LABEL maintainer="support@openc3.com"

USER root

ARG RUBYGEMS_URL=https://rubygems.org
ENV RUBYGEMS_URL=${RUBYGEMS_URL}
ARG PYPI_URL=https://pypi.org
ARG UV_VERSION=0.11.8
ENV PYPI_URL=${PYPI_URL}
ENV UV_VERSION=${UV_VERSION}

# We require a local certificate file so set that up.
# You must place a valid cacert.pem file in your OpenC3 development folder for this work
# Comment out these lines if this is not required in your environment
COPY cacert.pem /devel/cacert.pem
ENV SSL_CERT_FILE=/devel/cacert.pem
ENV CURL_CA_BUNDLE=/devel/cacert.pem
ENV REQUESTS_CA_BUNDLE=/devel/cacert.pem
ENV NODE_EXTRA_CA_CERTS=/devel/cacert.pem

ENV NOKOGIRI_USE_SYSTEM_LIBRARIES=1

COPY .gemrc /root/.gemrc
RUN sed -i "s|RUBYGEMS_URL|${RUBYGEMS_URL}|g" /root/.gemrc && \
    cp /root/.gemrc /etc/gemrc && \
    cp /root/.gemrc /usr/local/etc/gemrc

ENV GEMRC=/etc/gemrc

COPY *.tar.gz /tmp/

COPY anycable* /usr/bin
RUN /usr/bin/anycable_install.sh

COPY shoreman.sh /usr/bin/shoreman

ARG PACKAGES="gcc-c++ patch readline zlib zlib-devel libffi-devel libedit \
  openssl-devel make nc bzip2 autoconf automake libtool sqlite-devel libpq-devel \
  python3.12 python3.12-devel python3.12-pip python3.12-numpy ca-certificates less git \
  libpq-devel libxml2-devel libxslt-devel libyaml-devel cmake glibc-static vim procps unzip ncurses-devel"

RUN rm /etc/yum.repos.d/*
COPY ./ubi.repo /etc/yum.repos.d/ubi.repo

# ruby - https://www.ruby-lang.org/en/downloads/releases/
RUN microdnf update -y && \
    microdnf install -y --setopt=tsflags=nodocs $PACKAGES && \
    mkdir -p /usr/src && \
    tar -xzf /tmp/ruby-3.4.7.tar.gz -C /usr/src/ && \
    rm -f /tmp/ruby-3.4.7.tar.gz
WORKDIR /usr/src/ruby-3.4.7
RUN ./configure --disable-install-doc --enable-shared && \
    make -j "$(nproc)" && \
    make install && \
    rm -rf /usr/src/ruby-3.4.7

# tini - https://github.com/krallin/tini
WORKDIR /usr/src
RUN tar -xzf /tmp/tini-0.19.0.tar.gz && \
    rm -f /tmp/tini-0.19.0.tar.gz
WORKDIR /usr/src/tini-0.19.0
RUN CFLAGS="-DPR_SET_CHILD_SUBREAPER=36 -DPR_GET_CHILD_SUBREAPER=37" && \
    cmake . && \
    make && \
    make install && \
    rm -rf /usr/src/tini-0.19.0

WORKDIR /
RUN gem update --system 3.7.2 && \
    gem install rake && \
    gem install google-protobuf && \
    gem install grpc && \
    gem cleanup && \
    bundle config build.nokogiri --use-system-libraries && \
    bundle config git.allow_insecure true && \
    rm -rf /var/cache/dnf/ /var/tmp/* /tmp/* /var/tmp/.???* /tmp/.???* && \
    rm /bin/python && \
    rm /bin/python3 && \
    ln -s /bin/python3.12 /bin/python && \
    ln -s /bin/python3.12 /bin/python3 && \
    ln -s /bin/pip3.12 /bin/pip && \
    ln -s /bin/pip3.12 /bin/pip3 && \
    python3 -m pip install --break-system-packages uv=="${UV_VERSION}"

# Configure UV for production container usage
ENV UV_LINK_MODE=copy
ENV UV_COMPILE_BYTECODE=1
ENV UV_PYTHON_DOWNLOADS=never

# Set Python executable path for microservices (uses venv to support editable installs)
ENV OPENC3_PYTHON_BIN=/openc3/python/.venv/bin/python

# rbspy - https://github.com/rbspy/rbspy
COPY rbspy-x86_64-unknown-linux-gnu-0.39.0.tar.gz /opt/rbspy-x86_64-unknown-linux-gnu-0.39.0.tar.gz
WORKDIR /opt
RUN tar -xzf rbspy-x86_64-unknown-linux-gnu-0.39.0.tar.gz && \
    cp rbspy-x86_64-unknown-linux-gnu /usr/local/bin/rbspy && \
    chmod +x /usr/local/bin/rbspy && \
    rm rbspy-x86_64-unknown-linux-gnu && \
    rm rbspy-x86_64-unknown-linux-gnu-0.39.0.tar.gz

# htop - https://github.com/htop-dev/htop
COPY htop-3.4.1.tar.gz /opt/htop-3.4.1.tar.gz
WORKDIR /opt
RUN tar -xzf htop-3.4.1.tar.gz
WORKDIR /opt/htop-3.4.1
RUN ./autogen.sh && \
    ./configure && \
    make && \
    make install && \
    rm -rf /opt/htop-3.4.1 && \
    rm /opt/htop-3.4.1.tar.gz

# libsocketcan - used by libcsp - https://github.com/linux-can/libsocketcan
COPY libsocketcan-0.0.12.tar.gz /opt/libsocketcan-0.0.12.tar.gz
WORKDIR /opt
RUN tar -xzf libsocketcan-0.0.12.tar.gz
WORKDIR /opt/libsocketcan-0.0.12
RUN autoreconf --force --install --symlink -Wall && \
    ./configure --libdir=/usr/lib64 && \
    make && \
    make install && \
    rm -rf /opt/libsocketcan-0.0.12 && \
    rm /opt/libsocketcan-0.0.12.tar.gz

# libzmq - used by libcsp - https://github.com/zeromq/libzmq
COPY libzmq-34f7fa22022bed9e0e390ed3580a1c83ac4a2834.zip /opt/libzmq-34f7fa22022bed9e0e390ed3580a1c83ac4a2834.zip
WORKDIR /opt
RUN unzip libzmq-34f7fa22022bed9e0e390ed3580a1c83ac4a2834.zip
WORKDIR /opt/libzmq-34f7fa22022bed9e0e390ed3580a1c83ac4a2834/build
RUN cmake .. \
      -D WITH_PERF_TOOL=OFF \
      -D ZMQ_BUILD_TESTS=OFF \
      -D ENABLE_CPACK=OFF \
      -D CMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_LIBDIR=/usr/lib64 && \
    make && \
    make install && \
    rm -rf /opt/libzmq-34f7fa22022bed9e0e390ed3580a1c83ac4a2834 && \
    rm /opt/libzmq-34f7fa22022bed9e0e390ed3580a1c83ac4a2834.zip

# libcsp - https://github.com/libcsp/libcsp
COPY libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632.zip /opt/libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632.zip
WORKDIR /opt
RUN unzip libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632.zip && \
    # Patches to fix compilation issues
    sed -i '1s/^/#include <sys\/select.h>/' \
      libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632/src/drivers/can/can_socketcan.c && \
    sed -i '2s/^/#include <endian.h>/' \
      libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632/src/drivers/eth/eth_linux.c
WORKDIR /opt/libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632/build
RUN cmake .. -DCSP_ENABLE_PYTHON3_BINDINGS=ON -DCSP_USR_RTABLE=ON -DCMAKE_INSTALL_LIBDIR=/usr/lib64 && \
    make && \
    make install && \
    cp libcsp_py3* /lib64/python3.12/lib-dynload/. && \
    rm -rf /opt/libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632 && \
    rm /opt/libcsp-6b6e2dd2870bd1f8ab4516123f1fa255d6c1b632.zip

# Set user and group
ENV IMAGE_USER=openc3
ENV IMAGE_GROUP=openc3
ENV USER_ID=1001
ENV GROUP_ID=1001
# The build time venv is at /openc3/python/.venv and the runtime venv is at /gems/python_packages
# NOTE: This is declared as PYTHONUSERBASE: "/gems/python_packages" in compose.yaml
ENV PYTHONPATH=/openc3/python/.venv/lib/python3.12/site-packages/:/gems/python_packages/lib/python3.12/site-packages/
RUN groupadd -g ${GROUP_ID} ${IMAGE_GROUP}
RUN useradd -u ${USER_ID} -g ${IMAGE_GROUP} -s /bin/sh ${IMAGE_USER}

# Switch to user
USER ${USER_ID}:${GROUP_ID}

ENTRYPOINT [ "/usr/local/bin/tini", "--" ]
