const path = require("path");
const fs = require("fs");

/**
 * Simple glob matcher supporting * and ** patterns.
 * Converts a glob pattern to a regex for matching.
 */
function globMatch(str, pattern) {
  const regex = pattern
    .replace(/[.+^${}()|[\]\\]/g, "\\$&") // escape regex special chars (except * and ?)
    .replace(/\*\*/g, "\0") // placeholder for **
    .replace(/\*/g, "[^/]*") // * matches anything except /
    .replace(/\0/g, ".*") // ** matches anything including /
    .replace(/\?/g, "[^/]"); // ? matches single char except /
  return new RegExp(`^${regex}$`).test(str);
}

/**
 * Based on code from https://github.com/cmfcmf/docusaurus-search-local/
 * by Christian Flach, licensed under the MIT license.
 */
function generateMiniSearchClientJS(outDir) {
  const clientCode =
    "// THIS FILE IS AUTOGENERATED\n" +
    "// DO NOT EDIT THIS FILE!\n\n" +
    'import MiniSearch from "minisearch";\n' +
    "export default MiniSearch;\n";

  const clientPath = path.join(outDir, "lunr.client.js");
  fs.writeFileSync(clientPath, clientCode);
}

function getFilePaths(routesPaths, outDir, baseUrl, options = {}) {
  const files = [];
  const addedFiles = new Set();
  const {
    excludeRoutes = [],
    includeRoutes = [],
    indexBaseUrl = false,
  } = options;
  const meta = {
    excludedCount: 0,
  };

  routesPaths.forEach((route) => {
    if (route === `${baseUrl}404.html`) return;

    const isBaseUrl = route === baseUrl;

    if (isBaseUrl && !indexBaseUrl) {
      return;
    }

    const relativePath = route.replace(baseUrl, "");
    const candidatePaths = [route, relativePath].flatMap((route) => {
      return [
        path.join(outDir, `${route}.html`),
        path.join(outDir, route, "index.html"),
      ];
    });

    const filePath = candidatePaths.find(fs.existsSync);
    if (filePath && !fs.existsSync(filePath)) {
      console.warn(
        `docusaurus-search: could not resolve file for route '${route}', it will be missing in the search index`,
      );
    }

    // if we already added this file, skip it
    if (filePath && addedFiles.has(filePath)) return;

    // if we have include routes, skip if this route doesn't match any of them
    if (
      includeRoutes.length > 0 &&
      !includeRoutes.some(
        (includePattern) =>
          globMatch(route, includePattern) ||
          globMatch(relativePath, includePattern),
      )
    ) {
      meta.excludedCount++;
      return;
    }

    // if we have exclude routes, skip if this route matches any of them
    if (
      excludeRoutes.some(
        (excludePattern) =>
          globMatch(route, excludePattern) ||
          globMatch(relativePath, excludePattern),
      )
    ) {
      meta.excludedCount++;
      return;
    }

    files.push({
      path: filePath,
      url: route,
    });
    addedFiles.add(filePath);
  });
  return [files, meta];
}

module.exports = {
  generateMiniSearchClientJS,
  globMatch,
  getFilePaths,
};
