const path = require("node:path");
const fs = require("node:fs");

/**
 * Simple glob matcher supporting * and ** patterns.
 * Converts a glob pattern to a regex for matching.
 */
function globMatch(str, pattern) {
  const regex = pattern
    .replaceAll(/[.+^${}()|[\]\\]/g, String.raw`\$&`) // escape regex special chars (except * and ?)
    .replaceAll("**", "\0") // placeholder for **
    .replaceAll("*", "[^/]*") // * matches anything except /
    .replaceAll("\0", ".*") // ** matches anything including /
    .replaceAll("?", "[^/]"); // ? matches single char except /
  return new RegExp(`^${regex}$`).test(str);
}

/**
 * Based on code from https://github.com/cmfcmf/docusaurus-search-local/
 * by Christian Flach, licensed under the MIT license.
 */
/**
 * Generates a MiniSearch client module in the Docusaurus @generated directory.
 * This file re-exports MiniSearch so it can be imported at runtime via the
 * "@generated/mini-search.client" alias.
 * @param {string} outDir - The Docusaurus @generated files directory
 */
function generateMiniSearchClientJS(outDir) {
  const clientCode =
    "// THIS FILE IS AUTOGENERATED\n" +
    "// DO NOT EDIT THIS FILE!\n\n" +
    'import MiniSearch from "minisearch";\n' +
    "export default MiniSearch;\n";

  const clientPath = path.join(outDir, "mini-search.client.js");
  fs.writeFileSync(clientPath, clientCode);
}

/**
 * Resolves Docusaurus routes to their built HTML file paths on disk.
 * Skips the 404 page, deduplicates files, and applies include/exclude route
 * filters from plugin options.
 * @param {string[]} routesPaths - All route paths reported by Docusaurus
 * @param {string} outDir - The build output directory
 * @param {string} baseUrl - The site's base URL (e.g. "/")
 * @param {Object} options - Plugin options
 * @param {string[]} [options.excludeRoutes] - Glob patterns for routes to exclude
 * @param {string[]} [options.includeRoutes] - Glob patterns for routes to include (if set, only matching routes are indexed)
 * @param {boolean} [options.indexBaseUrl] - Whether to index the base URL page
 * @returns {[Array<{path: string, url: string}>, {excludedCount: number}]} Tuple of file list and metadata
 */
function getFilePaths(routesPaths, outDir, baseUrl, options = {}) {
  const files = [];
  const addedFiles = new Set();
  const {
    excludeRoutes = [],
    includeRoutes = [],
    indexBaseUrl = false,
  } = options;
  const meta = {
    excludedCount: 0,
  };

  routesPaths.forEach((route) => {
    if (route === `${baseUrl}404.html`) return;

    const isBaseUrl = route === baseUrl;

    if (isBaseUrl && !indexBaseUrl) {
      return;
    }

    const relativePath = route.replace(baseUrl, "");
    const candidatePaths = [route, relativePath].flatMap((route) => {
      return [
        path.join(outDir, `${route}.html`),
        path.join(outDir, route, "index.html"),
      ];
    });

    const filePath = candidatePaths.find((p) => fs.existsSync(p));
    if (!filePath) {
      console.warn(
        `docusaurus-search: could not resolve file for route '${route}', it will be missing in the search index`,
      );
      return;
    }

    // if we already added this file, skip it
    if (addedFiles.has(filePath)) return;

    // if we have include routes, skip if this route doesn't match any of them
    if (
      includeRoutes.length > 0 &&
      !includeRoutes.some(
        (includePattern) =>
          globMatch(route, includePattern) ||
          globMatch(relativePath, includePattern),
      )
    ) {
      meta.excludedCount++;
      return;
    }

    // if we have exclude routes, skip if this route matches any of them
    if (
      excludeRoutes.some(
        (excludePattern) =>
          globMatch(route, excludePattern) ||
          globMatch(relativePath, excludePattern),
      )
    ) {
      meta.excludedCount++;
      return;
    }

    files.push({
      path: filePath,
      url: route,
    });
    addedFiles.add(filePath);
  });
  return [files, meta];
}

module.exports = {
  generateMiniSearchClientJS,
  getFilePaths,
};
