ARG OPENC3_UBI_REGISTRY=registry1.dso.mil
ARG OPENC3_UBI_IMAGE=ironbank/redhat/ubi/ubi9-minimal
ARG OPENC3_UBI_TAG=9.6
ARG OPENC3_VERSITYGW_VERSION=v1.0.20

FROM ${OPENC3_UBI_REGISTRY}/${OPENC3_UBI_IMAGE}:${OPENC3_UBI_TAG}

ARG OPENC3_VERSITYGW_VERSION

# Copy both architecture tarballs and install script
# Tarball naming: versitygw_${VERSION}_Linux_${ARCH}.tar.gz
# Tarball structure: versitygw_${VERSION}_Linux_${ARCH}/versitygw
COPY versitygw_${OPENC3_VERSITYGW_VERSION}_Linux_*.tar.gz /tmp/
COPY versitygw_install.sh /tmp/
RUN chmod +x /tmp/versitygw_install.sh && /tmp/versitygw_install.sh

COPY cacert.pem /devel/cacert.pem
ENV SSL_CERT_FILE=/devel/cacert.pem
ENV CURL_CA_BUNDLE=/devel/cacert.pem
ENV REQUESTS_CA_BUNDLE=/devel/cacert.pem
ENV NODE_EXTRA_CA_CERTS=/devel/cacert.pem

COPY --chown=1001:1001 --chmod=755 docker-entrypoint.sh /usr/bin/

RUN microdnf update -y && \
    microdnf clean all && \
    rm -rf /var/cache/yum && \
    chmod +x /usr/bin/docker-entrypoint.sh && \
    mkdir -p /data && \
    chown 1001:1001 /data && \
    chmod -R 777 /data

USER 1001
EXPOSE 9000
VOLUME /data
ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
CMD ["versitygw"]
