# Copyright 2026 OpenC3, Inc.
# All Rights Reserved.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE.md for more details.

# This file may also be used under the terms of a commercial license
# if purchased from OpenC3, Inc.

name: Python Lint

on:
  pull_request:
    branches-ignore:
      - "dependabot/**"
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "openc3/python/**/*.py"
      - "openc3-cosmos-script-runner-api/scripts/**/*.py"
      - "openc3-cosmos-script-runner-api/test/**/*.py"
      - "openc3/python/pyproject.toml"
      - "openc3/python/uv.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ruff:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: true
          working-directory: openc3/python
      - name: Set up Python
        run: uv python install
        working-directory: openc3/python
      - name: Install dependencies
        run: uv sync --frozen
        working-directory: openc3/python
      - name: Run ruff check on openc3/python
        run: uv run --frozen ruff check --output-format=github openc3
        working-directory: openc3/python
      - name: Run ruff format check on openc3/python
        run: uv run --frozen ruff format --check openc3
        working-directory: openc3/python
      - name: Run ruff check on script-runner-api scripts
        run: uv run --frozen ruff check --output-format=github ../../openc3-cosmos-script-runner-api/scripts
        working-directory: openc3/python
      - name: Run ruff format check on script-runner-api scripts
        run: uv run --frozen ruff format --check ../../openc3-cosmos-script-runner-api/scripts
        working-directory: openc3/python
